---
title: "Creating & Working with Vectors"
author: "Victoria Cutler"
date: "2022-08-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(palmerpenguins)
```

### Make some vectors

```{r}
marmots <- c("blue", "green", 4, "yellow") ## vectors all have to have elements of the same class

## get in the habit of checking classes:
class(marmots)
```

```{r}
pika <- c(12.4,6.8,2.9,8.8,8.5)
class(pika)

## scalar multiplier
scalar_pika <- 5.2 * pika
scalar_pika
```

```{r}
bananas <- c(1, 2, 3)
apples <- c(6, 7, 8)

bananas + apples
bananas - apples

## dot product aka 1*6 + 2*7 + 3*8
bananas %*% apples
```

### Matrices

make some vectors then combine them to make a matrix, either adding them as rows or columns

```{r}
my_values <- seq(from = 1, to = 10) ##assumes by = 1 unless told otherwise ## could use "length = 200" and it will create 200 equally spaced values

my_matrix <- matrix(data = my_values, nrow = 2, ncol = 5, byrow = TRUE) ## so the matrix is filled going through each row
my_matrix

5 * my_matrix
```

###  

```{r}
glimpse(penguins) ##helpful to look at the classes at the whole data frame
```

hello
